services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/initdb:/docker-entrypoint-initdb.d
  nginx:
    image: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates